AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "*.gemspec"
  DisplayCopNames: true

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FileName:
  Enabled: false

Documentation:
  Enabled: false
